AWSTemplateFormatVersion: 2019.09.09

Parameters:
  Region:
    Description: aws region for pipepline
    Type: String
    Default: eu-west-1

Resources:
  artifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "sls-visma-course-artifact-bucket-hbay"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true